package pokemon;

public enum Blocks {
	BARRIER, BERRYSOIL, CAVE, CUT_TREE, DESERT, DOOR,
	FLOWER, PERSON, PLAYER, POKEBALL, PUDDLE, RIDGE, 
	ROCKSMASH_ROCK, SIGN, STANDARD, STRENGTH_BOULDER, 
	TALLGRASS, WATER, WATERFALL
}
