package pokemon;

public enum Blocks {
	BARRIER, BERRYSOIL, CAVE, CUT_TREE, DESERT, DOOR,
	FLOWER, PERSON, PLAYER, POKEBALL, POND, PUDDLE, RIDGE, 
	ROCKSMASH_ROCK, SIGN, SIGNBARRIER, STANDARD, STRENGTH_BOULDER, 
	TALLGRASS, TRAINERVIEW, WATER, WATERFALL
}
