package pokemon;

public enum PeopleType {
	BIKER, BIRDKEEPER, BLACKBELT, BREEDER, BUGMANIAC, COLLECTOR, DRAGONTAMER, 
	ELITEFOUR, EXPERT, FISHERMAN, GENTLEMAN, GENERIC, HIKER, INTERVIEWER, LADY, 
	GYMLEADER, NERD, NINJA, OFFICER, PROFESSOR, PSYCHIC, RANGER, RICHBOY, RICHGIRL,
	RIVAL, SAILOR, SCIENTIST, SWIMMER, TAMER, TEACHER, TRAINER, TUBER, YOUNGSTER
}